## numpy
shape
size
ndim

In [3]:
import numpy as np
#列表转化成矩阵
array=np.array([[1,2,3],
               [2,3,4]])
print(array)
print('number of dim:',array.ndim)
print('shape:',array.shape)
print('size:',array.size)

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape: (2, 3)
size: 6


## numpy 中创建矩阵
np.array()    
np.arange()   
np.zeros()    
np.ones()     
np.empty()     
np.linespace()    
dtype     
np.random.random()  
矩阵array数字之间没有逗号，而列表有逗号

In [24]:
import numpy as np
#array数字之间没有逗号，列表有逗号
#一维矩阵
a=np.array([1,34,5],dtype=float) #int是32 float是64
print(a.dtype)

#多维矩阵
b=np.array([ [1,2,3],
              [2,3,4]])
print(b)

#直接生成矩阵
#(行数，列数)注意一定要用单独再一个括号
c=np.zeros((3,4),dtype=int)
print(c)

d=np.ones((3,4),dtype=int)
print(d)

e=np.empty((3,4))
print(e)#生成的几乎都是零

f=np.arange(10,20,2)#生成有序的序列
print(f)

g=np.arange(12)#默认初始值为0，步长为1
print(g)
print('number of dim:',g.ndim)
print('shape:',g.shape)
print('size:',g.size)

h=np.arange(12).reshape((3,4))
print(h)

i=np.linspace(1,10,20)#从1到10 中间有20端
print(i)
print(i.reshape((4,5)))

float64
[[1 2 3]
 [2 3 4]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[10 12 14 16 18]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
number of dim: 1
shape: (12,)
size: 12
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
[[ 1.          1.47368421  1.94736842  2.42105263  2.89473684]
 [ 3.36842105  3.84210526  4.31578947  4.78947368  5.26315789]
 [ 5.73684211  6.21052632  6.68421053  7.15789474  7.63157895]
 [ 8.10526316  8.57894737  9.05263158  9.52631579 10.        ]]


## numpy中的矩阵运算
加法+    
减法-    
点乘*    
除法/     
乘方** 几次方就有几个*     
np.dot(a,b)=a.dot(b)          
np.sin()      
  

In [35]:
import numpy as np
a=np.array([10,20,30,40])
b=np.arange(4)
print(a,b)
c=a-b
print(c)
d=a*b#点乘
print(d)

#矩阵的乘法
g=np.dot(a,b)
print('g:',g)
e=b**2#次方
print(e)

#三角函数
f=10*np.sin(a)
print(f)

[10 20 30 40] [0 1 2 3]
[10 19 28 37]
[  0  20  60 120]
g: 200
[0 1 4 9]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [30]:
#比较
print(b<3)

[ True  True  True False]


In [37]:
import numpy as np
a=np.array([[1,1],
           [0,1]])
b=np.arange(4).reshape((2,2))
print(a)
print(b)

c=a*b
print('c:',c)
e=np.dot(a,b)
#或者可以写成a.dot(b)
print('e:',e)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
c: [[0 1]
 [0 3]]
e: [[2 4]
 [2 3]]


## 求和 取最大最小  
np.sum()      
np.max()      
np.min()     
axis=0 对列操作    
axis=1 对行操作

In [41]:
#随机生成
a=np.random.random((2,4))
print('a:',a)

print('sum:',np.sum(a))
print('对每一列求和：',np.sum(a,axis=0))
print('对每一行求和：',np.sum(a,axis=1))
print('max:',np.max(a))
print('对每一列求和:',np.max(a,axis=0))
print('对每一行求和:',np.max(a,axis=1))
print('min:',np.min(a))

a: [[0.10835958 0.58067124 0.67741057 0.48712016]
 [0.86835977 0.61518393 0.90858542 0.8404532 ]]
sum: 5.08614387246083
对每一列求和： [0.97671935 1.19585517 1.58599599 1.32757336]
对每一行求和： [1.85356155 3.23258232]
max: 0.9085854221023596
对每一列求和: [0.86835977 0.61518393 0.90858542 0.8404532 ]
对每一行求和: [0.67741057 0.90858542]
min: 0.10835957830544274


## 运算
np.argmin()  
np.argmax()    
np.mean()或者是np.average()或者a.mean()  
np.median()  
np.cumsum()   
np.diff()   
np.nonzeros()   
np.sort()  
np.transpose()  


In [69]:
import numpy as np
a=np.arange(2,14).reshape((3,4))
print('a:',a)
#输出a中最小的数的索引位置
print(np.argmin(a))
print(np.argmax(a))

#均值
print('mean:',np.mean(a))
print('每一列的平均值:\n',np.mean(a,axis=0))
print('每一行的平均值:\n',np.mean(a,axis=1))
#或者这么写
print(a.mean())
print('average:',np.average(a))
#不能这么写a.average()

#中位数
print('中位数median:',np.median(a))

#逐步累加累差
print('逐步累加:',np.cumsum(a))
print('每两个数之间的差:',np.diff(a))

#找出非零的数的行数和列数
print('非零的数:\n',np.nonzero(a))
#输出的内容中第一个array是非零数的行数，第二个array是非零数的列数

#排序
#默认对每一行进行升序排列
b=np.arange(14,2,-1).reshape((3,4))
print('b:\n',b)
print('升序排列:\n',np.sort(b))

a: [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
mean: 7.5
每一列的平均值:
 [6. 7. 8. 9.]
每一行的平均值:
 [ 3.5  7.5 11.5]
7.5
average: 7.5
中位数median: 7.5
逐步累加: [ 2  5  9 14 20 27 35 44 54 65 77 90]
每两个数之间的差: [[1 1 1]
 [1 1 1]
 [1 1 1]]
非零的数:
 (array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))
b:
 [[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
升序排列:
 [[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [67]:
#矩阵的转置
print('b:\n',b)
print('b的转置:\n',b.T)
#或者这么写
print('b的转置:\n',np.transpose(b))
#b*b的转置
print('b*b的转置:\n',(b.T).dot(b))

#数组的数值截断
print('所有大于9的数都是9，所有小于5的数都是5，之间的数就保留不变:\n',np.clip(b,5,9))

b:
 [[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
b的转置:
 [[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
b的转置:
 [[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
b*b的转置:
 [[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]
所有大于9的数都是9，所有小于5的数都是5，之间的数就保留不变:
 [[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


## numpy索引
根据位置找出值  


In [88]:
import numpy as np
#一维
a=np.arange(3,15)
print('a:\n',a)
print('a中位3的值:',a[3])
#二维
b=a.reshape((3,4))
print('b:\n',b)
print('b中位2的值(按行):',b[2])
print('第二行第一列的数是:',b[1][0])
#也可以这么写注意是中括号哦
print('第二行第一列的数是:',b[1,0])
#冒号代表所有的数字
print('第一列的所有值:\n',b[:,0])
print('第一行第2，3列的数:\n',b[1,1:3])

a:
 [ 3  4  5  6  7  8  9 10 11 12 13 14]
a中位3的值: 6
b:
 [[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
b中位2的值(按行): [11 12 13 14]
第二行第一列的数是: 7
第二行第一列的数是: 7
第一列的所有值:
 [ 3  7 11]
第一行第2，3列的数:
 [8 9]


In [94]:
print('打印出b中每一行的数')
for row in b:
    print(row)
    
print('打印出b中每一列的数')
for col in b.T: #转置一下原来的列就是现在的行了
    print(col)
    
print('打印出b中的每一个数字')
for item in b.flat:
    print(item)

    
#b.flat是一个迭代器
#b.flatten（）是把矩阵转换成一个序列
print('矩阵变数列:\n',b.flatten())

打印出b中每一行的数
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
打印出b中每一列的数
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
打印出b中的每一个数字
3
4
5
6
7
8
9
10
11
12
13
14
矩阵变数列:
 [ 3  4  5  6  7  8  9 10 11 12 13 14]


## 矩阵的合并
np.vstack(a,b,b) 等价于np.concatenate(（a,b,b）,axis=0)垂直竖直纵向合并   
np.hstack(a,b,b) 等价于np.concatenate(（a,b,b）,axis=1）水平横向合并  
a[np.newaxis,:]增加维度

In [113]:
import numpy as np
a=np.array([1,1,1])
b=np.array([2,2,2])

print('垂直上下的合并 vertical stack:\n',np.vstack((a,b)))
c=np.vstack((a,b))
print('a的shape:',a.shape,'\n','c的shape:',c.shape)

d=np.hstack((a,b))
print('水平左右合并:',d)

print(a.reshape((3,1)))
#转置不可以使一个行数列转置成列数列
#在行上面加一个维度
print('在行上面加一个维度:\n',a[np.newaxis,:])
print('此时他的shape是：',a[np.newaxis,:].shape)

print('在列上面加一个维度，就是一个纵向的数列的了:\n',a[:,np.newaxis])
print('此时他的shape是：',a[:,np.newaxis].shape)

A=np.array([1,1,1])[:,np.newaxis]
B=np.array([2,2,2])[:,np.newaxis]
print('A:\n',A)
print('B:\n',B)
C=np.hstack((A,B))
print('变成两个列序列之后的水平合并:\n',C)

#多个矩阵的合并
d=np.concatenate((A,B,B,A),axis=0)
print('把ABBA垂直合并:\n',d)
e=np.concatenate((A,B,B,A),axis=1)
print('把ABBA水平合并:\n',e)

垂直上下的合并 vertical stack:
 [[1 1 1]
 [2 2 2]
 [2 2 2]]
a的shape: (3,) 
 c的shape: (2, 3)
水平左右合并: [1 1 1 2 2 2]
[[1]
 [1]
 [1]]
在行上面加一个维度:
 [[1 1 1]]
此时他的shape是： (1, 3)
在列上面加一个维度，就是一个纵向的数列的了:
 [[1]
 [1]
 [1]]
此时他的shape是： (3, 1)
A:
 [[1]
 [1]
 [1]]
B:
 [[2]
 [2]
 [2]]
变成两个列序列之后的水平合并:
 [[1 2]
 [1 2]
 [1 2]]
把ABBA垂直合并:
 [[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
把ABBA水平合并:
 [[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


## 矩阵的分割
等量分割np.split(矩阵名字，块数，axis=0还是1)    
不等量分割np.array_split(矩阵名字，块数，axis=0还是1)
np.vsplit(矩阵名字，块数)   
np.hsplit()

In [124]:
import numpy as np
a=np.arange(12).reshape(3,4)
print('a:\n',a)

#要整除分割4列不能分成3块
print('纵向分割:\n',np.split(a,2,axis=1))
print('横向分割:\n',np.split(a,3,axis=0))

#不等量的分割每一块的维度可以不同
print('纵向不等量分割:\n',np.array_split(a,3,axis=1))

print('垂直纵向分成3块:\n',np.vsplit(a,3))
print('水平横向分成2块:\n',np.hsplit(a,2))



a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
纵向分割:
 [array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
横向分割:
 [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
纵向不等量分割:
 [array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
垂直纵向分成3块:
 [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
水平横向分成2块:
 [array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


## copy&deep copy

In [128]:
import numpy as np
a=np.arange(4)
print('a:',a)
b=a
c=a
d=b
a[0]=11
print('改变a之后，b与a相同吗:',b is a)
print('改变a之后，d与a相同吗:',d is a)
print('a,b,c,d都是指向同一个空间的，一个变化了，其他的都要变化:')

a: [0 1 2 3]
改变a之后，b与a相同吗: True
改变a之后，d与a相同吗: True
a,b,c,d都是指向同一个空间的，一个变化了，其他的都要变化:


In [131]:
a=np.arange(4)
print('a',a)
print('b',b)
b=a.copy()#deep copy 只是复制了值
print('a和b是指向两个不同的空间，只是空间中的数值相同')
a[3]=44
print('a:',a)
print('b:',b)

a [0 1 2 3]
b [0 1 2 3]
a和b是指向两个不同的空间，只是空间中的数值相同
a: [ 0  1  2 44]
b: [0 1 2 3]
